gdb/testsuite: fix unresolved test in gdb-caching-proc-consistency.exp
When running gdb.testsuite/gdb-caching-proc-consistency.exp with the
native-gdbserver board, I see an error reported:

  ERROR: gdbserver does not support attach 2036113 without extended-remote

and a test is reported UNRESOLVED:

   UNRESOLVED: gdb.testsuite/gdb-caching-proc-consistency.exp: testcase '<snip>/gdb.testsuite/gdb-caching-proc-consistency.exp' aborted due to Tcl error

The problem is that we are calling the can_spawn_for_attach_1 caching
proc directly, rather than through the can_spawn_for_attach wrapper
proc (which is not caching).

To fix this, in gdb-caching-proc-consistency.exp, I did consider
having 'test_file' spot 'can_spawn_for_attach_1' and test
'can_spawn_for_attach' instead, but that runs into problems as the
'test_proc' procedure does expect to be calling a caching proc, not a
non-caching wrapper proc.

I could make 'test_proc' smarter, but in the end I just opted to
replicate the condition checks from 'can_spawn_for_attach' inside the
'test_file' procedure, there's only two of them, this seems like the
easiest fix.

If we end up with more cases like this then it might be worth
restructuring things in here to better handle wrapper procs, but for
now that doesn't feel necessary.