sim/m32r: fix unused function warnings on non-Linux hosts
When building on macOS, I get:

    /Users/smarchi/src/binutils-gdb/sim/m32r/traps.c:141:1: error: unused function 't2h_addr' [-Werror,-Wunused-function]
      141 | t2h_addr (host_callback *cb, struct cb_syscall *sc,
          | ^~~~~~~~
    /Users/smarchi/src/binutils-gdb/sim/m32r/traps.c:158:1: error: unused function 'translate_endian_h2t' [-Werror,-Wunused-function]
      158 | translate_endian_h2t (void *addr, size_t size)
          | ^~~~~~~~~~~~~~~~~~~~
    /Users/smarchi/src/binutils-gdb/sim/m32r/traps.c:171:1: error: unused function 'translate_endian_t2h' [-Werror,-Wunused-function]
      171 | translate_endian_t2h (void *addr, size_t size)
          | ^~~~~~~~~~~~~~~~~~~~

These three helpers are only called from the TRAP_LINUX_SYSCALL case,
which is guarded by `#ifdef __linux__'.  Put them behind the same guard.

Change-Id: I8c8744727eb27abc08231be2a10f8d0de44d7ea6