gdbsupport: remove uses of sprintf
When building on macOS, I get some errors about the uses of sprintf:

      CXX      xml-utils.o
    /Users/smarchi/src/binutils-gdb/gdbsupport/xml-utils.cc:91:8: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
       91 |               sprintf (str, "%d", va_arg (ap, int));
          |               ^

We know they are safe, because the 32 byte destination buffer is large
enough for all conversions.  But I also don't think it's a big deal to
switch to xsnprintf to avoid these errors, and to catch any future
error.

Change-Id: If3531e1916e103dfccd0ec033639b14a2b6df3cf